### ISSUE TITLE
Cucumber configs broken on new versions of forge for 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [BlakeBr0/Cucumber#14]
**Describe the bug**
well it seems you might have empty comment stings that are causing your config to make a backup

**To Reproduce**
See Enderchests github issue here, https://github.com/ShetiPhian/Localizations-and-Issues/issues/293

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.42
 - Cucumber: 1.16.5-4.0.4.0

**Comment by BlakeBr0** [comment]
I do not. I just tested in a 1.16.5 instance and nothing out of the ordinary happened.

**Comment by ModernGamingWorld** [comment]
@BlakeBr0 Its still broken, so idk why close it when its not fixed

![explorer_mmiSxd64ZV](https://user-images.githubusercontent.com/75923060/108648529-16f9b980-7481-11eb-9f91-544e71d8b24b.png)

**Comment by ModernGamingWorld** [comment]
This proves it still broken

**Comment by BlakeBr0** [comment]
Logs? All you've done is make a false claim and show me a file in a folder?

Also I find it funny how something that has worked for years suddenly breaks for a ton of mods after a forge update and it's somehow not forge's fault.
