### ISSUE TITLE
Question on cucumber-tags.json

### ISSUE THREAD

**Issue by trogarus** [BlakeBr0/Cucumber#15]
I see in the latest release that you've suggested this updates and will reload. Playing on minecraft 1,16,5 with forge 36.1.30, and cucumber library 1.16.4-4.1.10 and this is all that's generating in the cucumber-tags.json

{
  "__comment": "Instructions: https://mods.blakebr0.com/docs/cucumber/tags-config"
}

I've even pulled out the file and placed it on my desktop to force regeneration of the file, but that doesn't seem to change it either.

**Comment by BlakeBr0** [comment]
Do you have mystical agriculture installed? It'll only generate entries that are needed by my other mods.

**Comment by trogarus** [comment]
I don’t have mystical installed, but I believe I have one or more of your other mods installed.  Full mod list at https://www.curseforge.com/minecraft/modpacks/trogarus-skyblock-bees-adventure

I am the pack dev and wanted to make sure this wasn’t an issue. Thanks for your mods and time to reply.

**Comment by BlakeBr0** [comment]
I think it's just MA that uses it currently, so I would say it's working as expected.
