### ISSUE TITLE
Tag lookup on logical client

### ISSUE THREAD

**Issue by rlnt** [BlakeBr0/Cucumber#22]
**Describe the bug**
In your custom recipe types and serializers, you send output tags across the network and use your TagMapper to resolve it on the client side to an actual item. This could cause visual bugs for recipes when configs are different on the server and on the client.

**To Reproduce**
Have a different preferred mod config on your client and on a dedicated server.

**Expected behavior**
The preferred item should be resolved on the logical server upon serialization **before** syncing recipes to the logical client to avoid synchronization issues. That way, the client gets the actual output item from the server and doesn't need to resolve the tag itself.

I could file a PR for this if you want.

**Comment by BlakeBr0** [comment]
I feel like there was a reason I did it this way. If there's a better solution I'm all for it.
