### ISSUE TITLE
Log Spam + Potential Crash

### ISSUE THREAD

**Issue by FooterManDev** [BlakeBr0/Cucumber#24]
**Describe the bug**
On 1.19.2 Cucumber likes to spam this in the log:
![image](https://user-images.githubusercontent.com/71946346/222535945-33bff899-c59f-4c65-858f-4700574a9ad8.png)
Very frequent, and annoying. I've also been having issues with `/reload` failing to work unless I reload the whole game, which I'm thinking is tagged to Cucumber in some way, but I'm not sure. Here's the [latest.log](https://gist.github.com/FooterMan14/5addd3996a57156913cb790c9abda9c9)

**To Reproduce**
Install Cucumber Library
Load the game.

**Expected behavior**
No log spam

**Screenshots / Scripts / Logs**
Latest.log posted ^

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.6
 - Cucumber: 6.0.6

**Comment by BlakeBr0** [comment]
What's the contents of the cucumber-tags.json file? Does deleting it fix it?

**Comment by FooterManDev** [comment]
![image](https://user-images.githubusercontent.com/71946346/222538527-2ffbb3f0-7144-4f3f-b3f7-0d98bf4f0cf1.png)
This is what's in the file. I'll go ahead and run the game without it, and after with a downgraded Cucumber version

**Comment by FooterManDev** [comment]
The log spam appears to be gone now after deleting the file, but I don't know if `/reload` is fixed.

**Comment by BlakeBr0** [comment]
I don't believe this issue would have caused any issues with /reload

**Comment by FooterManDev** [comment]
Yeah I don't think so either, after I got some mod updates the issue went away.
