### ISSUE TITLE
I cannt describe good my problem, so some error happend with cucumber when installing Create Steam's And Rails

### ISSUE THREAD

**Issue by Arginou57** [BlakeBr0/Cucumber#26]
**Describe the bug**
Server wont start cause cucumber error

**To Reproduce**
Start a server with cucumber ans Steam And Rails last version 

**Expected behavior**
I send the bugs at Author of Steam and rails, and tell me the bugs was on your side, cause compatibility i think

**Screenshots / Scripts / Logs**
[https://hastebin.com/share/aberaruvem.php]

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Cucumber: 1.19.2 6.0.7

**Comment by BlakeBr0** [comment]
The link expired but I believe it was a similar crash to https://github.com/BlakeBr0/IronJetpacks/issues/69.

Is this still an issue with the latest releases of both mods?

**Comment by BlakeBr0** [comment]
This should be fixed with Cucumber 6.0.8 and Iron Jetpacks 6.0.5.
