### ISSUE TITLE
Server Spam when Scythe tries to harvest Ars Magebloom

### ISSUE THREAD

**Issue by alfredggttv** [BlakeBr0/Cucumber#29]
**Describe the bug**
The server spams this message `[Cucumber Library/]: Unable to get seed from crop null` every tick. I found the cause. There was a Scythe in a modular router set to harvest an AoE. It wouldn't harvest the Magebloom seed (Ars Nouveau) and would spam that issue every time it would fail.

**To Reproduce**

1. Plant a Magebloom seed and another type of crop nearby.
2. Use a Scythe to harvest a seed nearby, and the AoE effect will not harvest the Magebloom.
3. The server console will get the outcome message.

**Expected behavior**

The plant becomes harvested, or the server console doesn't get spammed every time the action fails.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![spamlog](https://github.com/BlakeBr0/Cucumber/assets/107154056/2747b803-ccd1-4eaf-a4dd-2a9bde642391)
[2latest.log](https://github.com/BlakeBr0/Cucumber/files/12579235/2latest.log)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 7.0.1

**Comment by BlakeBr0** [comment]
Fixed in version 7.0.2 of Cucumber.
