### ISSUE TITLE
Game Crash When Creating World

### ISSUE THREAD

**Issue by DinnerBeef** [BlakeBr0/Cucumber#30]
**Describe the bug**
The game crashes when you try and create a new world.

**To Reproduce**
Try and create a new world

**Expected behavior**
Not To crash 

**Screenshots / Scripts / Logs**
https://s.dinnerbeef.com/gOXe5/wOXUsixA40.txt

Looks like there is very much related to https://github.com/BlakeBr0/IronJetpacks/issues/78.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Neo Forge: 47.1.76
 - Cucumber: 1.20.1-7.0.2

**Comment by BlakeBr0** [comment]
I couldn't reproduce it. Can you try this test build and see if it still happens? https://www.dropbox.com/scl/fi/y0h3csaibpcujofuhuxey/Cucumber-1.20.1-7.0.2-test.jar?rlkey=lp4zrkaiwjrrfdh55ivpdkbqq&dl=0

**Comment by DinnerBeef** [comment]
https://s.dinnerbeef.com/gOXe5/xAHowEMI04.png/raw

**Comment by BlakeBr0** [comment]
https://www.dropbox.com/scl/fi/sgc2xxc7m2691j82afgz7/Cucumber-1.20.1-7.0.2.jar?rlkey=iist3tvt0dxvz7svl2mf4lr9g&dl=0

**Comment by DinnerBeef** [comment]
Looks like the same thing. https://s.dinnerbeef.com/gOXe5/BUmEgaNA99.txt

**Comment by BlakeBr0** [comment]
https://www.dropbox.com/scl/fi/ik564cb9diuz75w6wmu6a/Cucumber-1.20.1-7.0.2.jar?rlkey=s55c78khg81drq01xokrhvid1&dl=0

If this doesn't work then I have no idea. Probably some sort of weird mod interactions

**Comment by DinnerBeef** [comment]
🥳 🥳 🥳 
![image](https://github.com/BlakeBr0/Cucumber/assets/8346986/a4626ff6-fb89-40cb-aa92-a5fd28f8c205)
🥳 🥳 🥳

**Comment by BlakeBr0** [comment]
I'll do a new release with the fix.
