### ISSUE TITLE
Mystical Agriculture/Agradditions or Cucumber newest update preventing Forge Server from starting.

### ISSUE THREAD

**Issue by Slessmanman** [BlakeBr0/Cucumber#32]
**Describe the bug**
I am trying to run both Mystical Agriculture and Mystical Agradditions, as well as cucumber, on my Forge Server (47.2.0). All of the previous versions (7.0.6, 7.0.1, and 7.0.4 respectively) run perfectly fine, but after updating all 3 to the versions released on 11/26/2023, the server refuses to start.

**To Reproduce**
I am just updating all JAR files from pre 11/26 releases of Agriculture/Agradditions/Cucumber to post 11/26 versions. going from (7.0.6, 7.0.1, and 7.0.4) to (7.0.7, 7.0.2, and 7.0.5) and executing 'run.bat' to launch the server normally.

**Expected behavior**
I expect the server to start as it did before updating.

**Screenshots / Scripts / Logs**
Attached is the contents of the cmd when attempting to run the server.
[Errormessage.txt](https://github.com/BlakeBr0/Cucumber/files/13478585/Errormessage.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.7
 - Cucumber: 7.0.4
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
Fixed in version 7.0.6, sorry about that!
