### ISSUE TITLE
Allthemods 9 Watering can crash loop

### ISSUE THREAD

**Issue by NickFDI** [BlakeBr0/Cucumber#33]
**Describe the bug**
After creating an awakened supremium watering can I filled it with water. After filling I attempted to water essence plants from mystical agriculture, a series of multiple plants, steel essence, coal, netherite, dragon essence, iron, gold, and a couple more. Upon dropping from the sky with a jetpack onto the plants and holding my "shift" or crouch key I was crashed from the game locally. No one else on the server was affected. I am unable to join back into the server, I will have to have the can removed from my inventory via the metadata. 

**To Reproduce**
Create awakened supremium watering can. Fill the can with water. Crouch while attempting to water different kinds of essence plants. 

**Expected behavior**
I expected the watering can to increase crop growth speed as intended. This works with all cans, this is the first issue. 

**Screenshots / Scripts / Logs**
[Minecraft Crash Report.txt](https://github.com/BlakeBr0/Cucumber/files/13623943/Minecraft.Crash.Report.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.8
 - Cucumber: Cucumber Library (cucumber), Version: 7.0.6
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
So that error appears to indicate that the watering can sound wasn't registered. Is there any errors in the logs on your client? Maybe something happened during startup that caused some weirdness with sound registration.

**Comment by NickFDI** [comment]
Hey, late response. I have no time at the moment to chase this issue further, If I ever come across it again I'll re-open with further evaluation / testing. Thanks for the response.
