### ISSUE TITLE
Cucumber Tags Not Importing Correcly

### ISSUE THREAD

**Issue by TwitchSoupsux** [BlakeBr0/Cucumber#36]
**Describe the bug**
Currently Playing Rangamod VII on an apexhosting server that me and my friends run, Ragnamod resource generation was a pain so we decided to add Mystical Agriculture V.1.18.2-5.15 and Cucumber 1.18.2-5.15. Unfortunately it will not allow us to craft the essence to the corresponding ingots even though the crafting recipes were imported in the cucumber file. 
**To Reproduce**
N/A
**Expected behavior**
N/A
**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![image_2024-05-25_122549064](https://github.com/BlakeBr0/Cucumber/assets/131203380/3ef86b8c-c5c4-4790-b6c2-9171d918da90)
![image_2024-05-25_122621172](https://github.com/BlakeBr0/Cucumber/assets/131203380/a3958e35-0662-4222-aa9b-5034e299719b)
![image_2024-05-25_122730236](https://github.com/BlakeBr0/Cucumber/assets/131203380/28cae06c-4d3b-4431-a51c-aedcfff9d468)
![Screenshot 2024-05-25 122706](https://github.com/BlakeBr0/Cucumber/assets/131203380/113f5d4a-4197-484a-b116-da140eb76735)

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.2.21
 - Cucumber: 5.15
 - Singleplayer or Multiplayer: Multiplayer
If you could tell me what I'm doing wrong or if this a known issue I would greatly appreciate it.

**Comment by BlakeBr0** [comment]
Does it work in a different crafting table? There may be something that conflicts with the custom recipe system some of the essence recipes use. Do essences for vanilla items work, or bronze for example?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
