### ISSUE TITLE
[1.21.1-NeoForge] Crash with AlmostUnified?

### ISSUE THREAD

**Issue by Gbergz** [BlakeBr0/Cucumber#39]
**Describe the bug**
When joining a world with AlmostUnified installed the game crashes.

**To Reproduce**
Install AlmostUnified
Install Cucumber
Enter world.
Crash. (Exception in server tick loop | java.lang.NoClassDefFoundError: com/almostreliable/unified/api/AlmostUnifiedLookup)

**Expected behavior**
No crash.

**Screenshots / Scripts / Logs**
https://gist.githubusercontent.com/Gbergz/d745cc403adb41e1ae61913ad17b47be/raw/fbe3f703d4c53c43b6ed3c5c4258d460067e5e5b/gistfile1.txt

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.23
 - Cucumber: 8.0.1 | https://legacy.curseforge.com/minecraft/mc-mods/cucumber/files/5654155
 - AlmostUnified: 1.0.0 | https://legacy.curseforge.com/minecraft/mc-mods/almost-unified/files/5654279
 - Singleplayer or Multiplayer: Singleplayer world
 
 **Notes**
 - I haven't tested with just those mods, as I didn't have time as of writing this, this was reproduced in a modpack (TNP Limitless 8).

**Comment by rlnt** [comment]
A pull request for this is already in place https://github.com/BlakeBr0/Cucumber/pull/38
