### ISSUE TITLE
cucumber-tags.json is invalid

### ISSUE THREAD

**Issue by diefesson** [BlakeBr0/Cucumber#42]
**Describe the bug**

Cucumber keeps generating invalid JSON for `cucumber-tags.json`

**To Reproduce**
 
1. Just run the mod with MA

**Expected behavior**

Cucumber shoud generate valid JSON for `cucumber-tags.json`

**Screenshots / Scripts / Logs**

~~~~ json
{
  "forge:ingots/enderium": "null",
  "forge:ingots/mithril": "null"
}}
~~~~

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: NeoForge 47.1.106
 - Cucumber: 7.0.12
 - Singleplayer or Multiplayer: singleplayer

**Comment by BlakeBr0** [comment]
Is this a consistent issue? If you delete the file and let it regenerate does it do the same thing? I'm honestly not sure why this would happen.

**Comment by diefesson** [comment]
Yes. It's a consistent issue. But I think it's caused in combination with some other mod. I am still trying to isolate it.

Maybe something related to a broken tag on load/reload?
