### ISSUE TITLE
Cucumber Library 1.14.4

### ISSUE THREAD

**Issue by robokinggage** [BlakeBr0/Cucumber#5]
this is what i keep getting when i try to load minecraft sometimes it works but other times it doesn't. i don't know what to do so i'm hopping you can fix it... image of the minecraft error below
![Minecraft 1 14 4 8_22_2019 5_27_51 PM](https://user-images.githubusercontent.com/54419494/63551278-ac219800-c502-11e9-9b4f-13fadcd38e5e.png)
This crash report below
I don't have it just yet when i get it i will add it...

**Comment by BlakeBr0** [comment]
What version of forge and cucumber are you using?

**Comment by Jarococo** [comment]
I am having the same problem, am using Minecraft Forge - MC 1.14.4 and Cucumber-1.14.4-2.0.2.jar. But instead of showing "*Cucumber Library (cucumber)* encountered an error during the side-setup event phase", it shows *has failed to load correctly".

**Comment by BlakeBr0** [comment]
Logs would be helpful

**Comment by Jarococo** [comment]
Forget it, when I updated to the version that supports the newest version of Forge the game loaded correctly. Thanks for the attention.

**Comment by robokinggage** [comment]
I haven't had the problem happen since the day I posted the issue that's
why I wasn't able to give the crash log for that issue. After I got done
posting that I went and re-downloaded it and I didn't really have any
issues after that it was still the same version of cucumber Library at the
time though.
